---
- hosts: web
  tasks:
   - name: install apache and git packages
     package: name={{item}} state=present
     with_items:
       - httpd
       - git
       - wget
   - name: start service httpd
     service: name=httpd state=started enabled=yes
     become: yes
   - name: get repo from git hub
     git: repo=https://github.com/demoglot/html-samples-doctor.git dest=/var/www/html
